filebeat.inputs:
  - type: docker
    containers:
      path: "/usr/share/dockerlogs/data"
      stream: "stdout"
      ids:
        - "*"
      cri.parse_flags: true
      combine_partial: true
      exclude_files: ['\.gz$']
 
processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
 
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
 
output.logstash:
  hosts: ["localhost:5044"]
  ssl.certificate_authorities:
   - /usr/share/elasticsearch/config/certificates/ca/ca.crt       
  ssl.certificate: "/usr/share/elasticsearch/config/certificates/logstash/logstash.crt"
  ssl.key: "/usr/share/elasticsearch/config/certificates/logstash/logstash.key"

log files:
logging.level: error
logging.to_files: false
logging.to_syslog: false
loggins.metrice.enabled: false
logging.files:
  path: /var/log/filebeat
  name: beats
  keepfiles: 7
  permissions: 0644
