version: "3.2"

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: create_certs
    command: >
     bash -c '
        yum install -y -q -e 0 unzip;
        yum install -y -q -e 0 openssl;
        yum install -y -q -e 0 java-1.8.0-openjdk;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
          openssl pkcs8 -in /certs/logstash/logstash.key -topk8 -nocrypt -out /certs/logstash/logstash.pkcs8.key;
          keytool -noprompt -import -alias elk -file /certs/ca/ca.crt -keystore /certs/ca/ca.jks -storepass ${JKS_PASSWORD};
        fi;
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - type: bind
        source: $ELK_STACK_DIR/certificates
        target: /certs
      - type: bind
        source: .
        target: $CERTS_DIR  
    networks:
      - elk_stack

networks:
  elk_stack:
    driver: bridge
